version: '3.8'
services:
    base:
        container_name: base
        image: ${COMPOSE_NAME}/${BASE_IMAGE}
        build:
            context: .
            args:
                - NODE_VERSION=${NODE_VERSION}
            dockerfile: base.Dockerfile
