version: '3.8'
services:
    ambrosia-postgres:
        image: ${COMPOSE_NAME}/${DATABASE_IMAGE}
        container_name: ambrosia-postgres
        build:
            context: .
            dockerfile: ./apps/postgres/pg.Dockerfile
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        networks:
            - 'ambrosia'
        volumes:
            - database:/${WORKINGDIR}/database
        # Remove these probably
        expose:
            - ${POSTGRES_PORT}
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
        # Remove these probably
    ambrosia-api:
        image: ${COMPOSE_NAME}/${API_IMAGE}
        depends_on:
            - ambrosia-postgres
        build:
            context: .
            dockerfile: ./apps/api/Dockerfile
            args:
                - WORKINGDIR=${WORKINGDIR}
                - COMPOSE_NAME=${COMPOSE_NAME}
                - BASE_IMAGE=${BASE_IMAGE}
                - NODE_VERSION=${NODE_VERSION}
        hostname: ${API_IMAGE}
        container_name: ${API_IMAGE}
        networks:
            - 'ambrosia'
        environment:
            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
        ports:
            - '80:80'
        expose:
            - 80
    ambrosia-website:
        image: ${COMPOSE_NAME}/${WEBSITE_IMAGE}
        hostname: ${WEBSITE_IMAGE}
        container_name: ${WEBSITE_IMAGE}
        build:
            context: .
            dockerfile: ./apps/website/Dockerfile
            args:
                - WORKINGDIR=${WORKINGDIR}
                - COMPOSE_NAME=${COMPOSE_NAME}
                - BASE_IMAGE=${BASE_IMAGE}
                - NGINX_VERSION=${NGINX_VERSION}
                - NGINX_PORT=${NGINX_PORT}
        networks:
            - 'ambrosia'
        environment:
            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
            - NGINX_PORT=${NGINX_PORT}
        expose:
            - ${NGINX_PORT}
    ambrosia-nginx:
        depends_on:
            - ambrosia-website
            - ambrosia-api
        hostname: ${NGINX_IMAGE}
        container_name: ${NGINX_IMAGE}
        image: ${COMPOSE_NAME}/${NGINX_IMAGE}
        build:
            context: .
            dockerfile: ./apps/nginx/Dockerfile
            args:
                - WORKINGDIR=${WORKINGDIR}
                - COMPOSE_NAME=${COMPOSE_NAME}
                - BASE_IMAGE=${BASE_IMAGE}
                - NGINX_VERSION=${NGINX_VERSION}
        networks:
            - 'appleptr16'
            - 'ambrosia'
        environment:
            - WEBSITE_DOMAIN=${WEBSITE_DOMAIN}
            - WEBSITE_IMAGE=${WEBSITE_IMAGE}
            - API_DOMAIN=${API_DOMAIN}
            - API_IMAGE=${API_IMAGE}

            - DOMAIN_PREFIX=${DOMAIN_PREFIX}
            - NGINX_PORT=${NGINX_PORT}

            - PORT=${NGINX_PORT}
            - WORKINGDIR=${WORKINGDIR}
        expose:
            - ${NGINX_PORT}
networks:
    appleptr16:
        name: appleptr16
    ambrosia:
volumes:
    database:
